######################################################################
# Automatically generated by qmake (2.01a) ?? 1? 30 08:36:50 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h screen.h snake.h
SOURCES += main.cpp mainwindow.cpp screen.cpp snake.cpp
